metadata.format.version = "1.1"

[versions]
accessWidener = "2.1.0"
asm = "9.6"
checkstyle = "10.12.5"
gson = "2.10.1"
gross = "1.3.3"
jetbrains = "24.1.0"
mixin = "0.12.5+mixin.0.8.5"
mixinExtras = "0.3.2"
nexus = "2.0.0-rc-1"
shadow = "7.1.2"
spotless = "6.13.0"
tinylog = "2.6.2"

[libraries]
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains" }

# logger
tinylog-api = { module = "org.tinylog:tinylog-api", version.ref = "tinylog" }
tinylog-impl = { module = "org.tinylog:tinylog-impl", version.ref = "tinylog" }

# loader
accessWidener = { module = "net.fabricmc:access-widener", version.ref = "accessWidener" }
asm = { module = "org.ow2.asm:asm", version.ref = "asm" }
asm-analysis = { module = "org.ow2.asm:asm-analysis", version.ref = "asm" }
asm-commons = { module = "org.ow2.asm:asm-commons", version.ref = "asm" }
asm-tree = { module = "org.ow2.asm:asm-tree", version.ref = "asm" }
asm-util = { module = "org.ow2.asm:asm-util", version.ref = "asm" }
mixin = { module = "net.fabricmc:sponge-mixin", version.ref = "mixin" }
mixinExtras = { module = "io.github.llamalad7:mixinextras-common", version.ref = "mixinExtras" }
gross = { module = "cpw.mods:grossjava9hacks", version.ref = "gross" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

# build
stylecheck = "ca.stellardrift:stylecheck:0.1"

build-nexus = { module = "io.github.gradle-nexus:publish-plugin", version.ref = "nexus" }
build-shadow = { module = "gradle.plugin.com.github.johnrengelman:shadow", version.ref = "shadow" }
build-spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }

# unused, for renovate
zCheckstyle = { module = "com.puppycrawl.tools:checkstyle", version.ref = "checkstyle" }

[plugins]
nexusPublish = { id = "io.github.gradle-nexus.publish-plugin", version = "2.0.0-rc-1" }
